services:
  rca-org0:
   container_name: rca-org0
   image: hyperledger/fabric-ca
   command: /bin/bash -c 'fabric-ca-server start -d -b org0-ca-admin:org0caadmin2023 --port 7053'
   extra_hosts:
     - host.docker.internal:host-gateway
   environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    #  - FABRIC_CA_SERVER_TLS_KEYSTORE=/tmp/hyperledger/fabric-ca/tls/msp/keystore/5f32133dd5a687e44951fdf03642833a1c2b16cd79be524626aad562df08099f_sk
    #  - FABRIC_CA_SERVER_TLS_CERTFILE=/tmp/hyperledger/fabric-ca/tls/msp/signcerts/cert.pem
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0,localhost,127.0.0.1,rca-org0,host.docker.internal,host-gateway
      - FABRIC_CA_SERVER_DEBUG=true
   volumes:
      - /tmp/hyperledger/org0/ca:/tmp/hyperledger/fabric-ca

   ports:
      - 7053:7053
  orderer1-org0:
   container_name: orderer1-org0
   image: hyperledger/fabric-orderer
   extra_hosts:
     - host.docker.internal:host-gateway
   environment:
     - ORDERER_HOME=/tmp/hyperledger/orderer
     - ORDERER_HOST=orderer1-org0
     - ORDERER_GENERAL_LISTENADDRESS=orderer1-org0
     - ORDERER_GENERAL_LISTENPORT=7050
     - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
     - ORDERER_GENERAL_LOCALMSPID=org0MSP
     - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org0/orderer/msp
     - ORDERER_GENERAL_TLS_ENABLED=true
     - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_GENERAL_TLS_ROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
     - ORDERER_GENERAL_LOGLEVEL=debug
     - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
     - ORDERER_CHANNELPARTICIPATION_ENABLED=true
     - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
     - ORDERER_ADMIN_TLS_ENABLED=true
     - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_ADMIB_TLS_CLIENTAUTHREQUIRED=true
     - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

   volumes:
     - /tmp/hyperledger/org0/orderer1:/tmp/hyperledger/org0/orderer/
   ports:
     - 7041:7050
     - 7031:9443

  orderer2-org0:
   container_name: orderer2-org0
   image: hyperledger/fabric-orderer
   extra_hosts:
     - host.docker.internal:host-gateway
   environment:
     - ORDERER_HOME=/tmp/hyperledger/orderer
     - ORDERER_HOST=orderer2-org0
     - ORDERER_GENERAL_LISTENADDRESS=orderer2-org0
     - ORDERER_GENERAL_LISTENPORT=7050
     - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
     - ORDERER_GENERAL_LOCALMSPID=org0MSP
     - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org0/orderer/msp
     - ORDERER_GENERAL_TLS_ENABLED=true
     - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_GENERAL_TLS_ROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
     - ORDERER_GENERAL_LOGLEVEL=debug
     - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
     - ORDERER_CHANNELPARTICIPATION_ENABLED=true
     - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
     - ORDERER_ADMIN_TLS_ENABLED=true
     - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_ADMIB_TLS_CLIENTAUTHREQUIRED=true                                                    
     - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

   volumes:
     - /tmp/hyperledger/org0/orderer2:/tmp/hyperledger/org0/orderer/
   ports:
     - 7042:7050
     - 7032:9443
  orderer3-org0:
   container_name: orderer3-org0
   image: hyperledger/fabric-orderer
   extra_hosts:
     - host.docker.internal:host-gateway
   environment:
     - ORDERER_HOME=/tmp/hyperledger/orderer
     - ORDERER_HOST=orderer1-org0
     - ORDERER_GENERAL_LISTENADDRESS=orderer3-org0
     - ORDERER_GENERAL_LISTENPORT=7050
     - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
     - ORDERER_GENERAL_LOCALMSPID=org0MSP
     - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org0/orderer/msp
     - ORDERER_GENERAL_TLS_ENABLED=true
     - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_GENERAL_TLS_ROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
     - ORDERER_GENERAL_LOGLEVEL=debug
     - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
     - ORDERER_CHANNELPARTICIPATION_ENABLED=true
     - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
     - ORDERER_ADMIN_TLS_ENABLED=true
     - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem
     - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/tls-msp/keystore/tls-key.pem
     - ORDERER_ADMIB_TLS_CLIENTAUTHREQUIRED=true                                                    
     - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem

   
   volumes:
     - /tmp/hyperledger/org0/orderer3:/tmp/hyperledger/org0/orderer/
   ports:
     - 7043:7050
     - 7033:9443
