###########################
#                         #
#   CONFIGURATION FILE    #
#                         #
###########################

# This file contains the configuration for the application.
# In this file the configuration for IOP server, IOP client and the Blockchain platforms , which are connected to this program, are defined.

#CERTIFICATE AUTHORITY (FOR gRPC SERVER)
ca:
  # The path to the certificate authority
  cert_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/ca-cert.pem
  # The password for the certificate authority
  key_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/ca-key.pem
#SERVER CONFIGURATION
server:
  # The port on which the server is listening
  port: 50051
  # Server certificate
  cert_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/server-cert.pem
  # Server private key
  key_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/server-key.pem

#CLIENT CONFIGURATION
#Here are the configuration for the client gRPC server which is supposed to connect to accessible networks
#This information contains the path to the specific  certificate and the key that each accessible network has provided.
#It is an array that contains port, client certificate and client private key for each accessible network, in addition to certificate of the CA of each accessible network.
client:
    - accessible_network_id:  AccessibleNetwork_koosha-dell.com_10
      accessible_network_name: koosha-dell
      company_name: k-dell
      cert_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/client-cert.pem
      port: 50051 #the outsider server port
      ip: 127.0.0.1 #the outsider server ip
      address: koosha-dell.com #the outsider server address
      key_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/client_key.pem
      ca_cert_path: /home/koosha/Desktop/Automated-Gateways/relay/certs/ca-cert.pem

#PLATFORMS CONFIGURATION
platform:
  hyperledger:
    name: Local_HyperledgerFabric_2.5.3
    msp_id: Org1MSP
    cert_path: /home/koosha/Desktop/Automated-Gateways/relay/internal/onchain/chain_certs/user_cert.pem
    key_path: /home/koosha/Desktop/Automated-Gateways/relay/internal/onchain/chain_certs/user_key.pem
    tls_cert_path: /home/koosha/Desktop/Automated-Gateways/relay/internal/onchain/chain_certs/ca.crt
    peer_endpoint: localhost:7051
    gateway_peer: peer0.org1.example.com
    accessible_network_channel_name : mychannel
    accessible_network_chaincode_name : accessible_net
    permitted_network_channel_name : mychannel
    permitted_network_chaincode_name : permitted_net
    permitted_method_channel_name : mychannel
    permitted_method_chaincode_name : permitted_method
    iop_history_chaincode_name : iop_history
    iop_history_channel_name : mychannel
