// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: scripts/iop.proto

package scripts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IOPClient is the client API for IOP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IOPClient interface {
	GetPermittedNetworkInfo(ctx context.Context, in *PermittedNetworkAddress, opts ...grpc.CallOption) (IOP_GetPermittedNetworkInfoClient, error)
}

type iOPClient struct {
	cc grpc.ClientConnInterface
}

func NewIOPClient(cc grpc.ClientConnInterface) IOPClient {
	return &iOPClient{cc}
}

func (c *iOPClient) GetPermittedNetworkInfo(ctx context.Context, in *PermittedNetworkAddress, opts ...grpc.CallOption) (IOP_GetPermittedNetworkInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &IOP_ServiceDesc.Streams[0], "/IOP/getPermittedNetworkInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &iOPGetPermittedNetworkInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IOP_GetPermittedNetworkInfoClient interface {
	Recv() (*PermittedNetworkInfo, error)
	grpc.ClientStream
}

type iOPGetPermittedNetworkInfoClient struct {
	grpc.ClientStream
}

func (x *iOPGetPermittedNetworkInfoClient) Recv() (*PermittedNetworkInfo, error) {
	m := new(PermittedNetworkInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IOPServer is the server API for IOP service.
// All implementations must embed UnimplementedIOPServer
// for forward compatibility
type IOPServer interface {
	GetPermittedNetworkInfo(*PermittedNetworkAddress, IOP_GetPermittedNetworkInfoServer) error
	mustEmbedUnimplementedIOPServer()
}

// UnimplementedIOPServer must be embedded to have forward compatible implementations.
type UnimplementedIOPServer struct {
}

func (UnimplementedIOPServer) GetPermittedNetworkInfo(*PermittedNetworkAddress, IOP_GetPermittedNetworkInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPermittedNetworkInfo not implemented")
}
func (UnimplementedIOPServer) mustEmbedUnimplementedIOPServer() {}

// UnsafeIOPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOPServer will
// result in compilation errors.
type UnsafeIOPServer interface {
	mustEmbedUnimplementedIOPServer()
}

func RegisterIOPServer(s grpc.ServiceRegistrar, srv IOPServer) {
	s.RegisterService(&IOP_ServiceDesc, srv)
}

func _IOP_GetPermittedNetworkInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PermittedNetworkAddress)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IOPServer).GetPermittedNetworkInfo(m, &iOPGetPermittedNetworkInfoServer{stream})
}

type IOP_GetPermittedNetworkInfoServer interface {
	Send(*PermittedNetworkInfo) error
	grpc.ServerStream
}

type iOPGetPermittedNetworkInfoServer struct {
	grpc.ServerStream
}

func (x *iOPGetPermittedNetworkInfoServer) Send(m *PermittedNetworkInfo) error {
	return x.ServerStream.SendMsg(m)
}

// IOP_ServiceDesc is the grpc.ServiceDesc for IOP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IOP",
	HandlerType: (*IOPServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getPermittedNetworkInfo",
			Handler:       _IOP_GetPermittedNetworkInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scripts/iop.proto",
}
